apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pgabjyo0r-python 
  janus-idp.io/tekton: pgabjyo0r-python
  backstage.io/kubernetes-id: pgabjyo0r-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pgabjyo0r-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  